name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Check if build outputs exist
      run: |
        test -f dist/esm/index.js || (echo "dist/esm/index.js not found" && exit 1)
        test -f dist/cjs/index.js || (echo "dist/cjs/index.js not found" && exit 1)
        test -f dist/browser/index.js || (echo "dist/browser/index.js not found" && exit 1)
        test -f dist/esm/index.d.ts || (echo "dist/esm/index.d.ts not found" && exit 1)
        echo "All build outputs present!"
